@FP.Api_HostAddress = http://localhost:5103

GET {{FP.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{FP.Api_HostAddress}}/api/operation/year/2024/month/11
Accept: application/json

###

GET https://localhost:7161/api/category
Accept: application/json