// <auto-generated />
using System;
using FP.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FP.Infrastructure.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20241110142452_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FP.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dcdbc0c0-6399-4dbe-bfc6-39351b86763d"),
                            Color = "#FF5733",
                            Name = "Needs",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("79de3e51-3b72-48c1-9eb1-c48c7cdce746"),
                            Color = "#FFC300",
                            Name = "Wants",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a32456f2-e734-47a0-b736-b734bd655226"),
                            Color = "#28A745",
                            Name = "Savings",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("3f1c9129-9a5e-4b04-b929-3e3dc2aca725"),
                            Color = "#8E44AD",
                            Name = "Subscriptions",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("4ed9c859-14c8-4866-a256-fd2b0aaa68e4"),
                            Color = "#FF6347",
                            Name = "Presents",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("9fb465b5-3097-4641-befe-43e8916a9d3b"),
                            Color = "#3498DB",
                            Name = "Salary",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("401f1c6d-9765-4341-81c7-87e16d09e93e"),
                            Color = "#1ABC9C",
                            Name = "Investments",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("3e57aa1c-6763-4ad4-8093-1880069e914b"),
                            Color = "#E74C3C",
                            Name = "Loans",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("4c3397c9-f22a-413d-b4f7-b45aa0369350"),
                            Color = "#F39C12",
                            Name = "Bonuses",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("addc0b03-b632-4c50-98f4-94871bef630e"),
                            Color = "#9B59B6",
                            Name = "Entertainment",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("f6b969f9-5d39-4d46-a021-d17523980ce6"),
                            Color = "#2ECC71",
                            Name = "Freelance",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("f4743f89-f9da-4697-999b-45147423cce3"),
                            Color = "#2980B9",
                            Name = "Education",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("f536adb6-c623-43c4-abfb-635568ce941b"),
                            Color = "#C0392B",
                            Name = "Health",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("ce9f563c-a479-419c-a1e9-15cf38f00209"),
                            Color = "#27AE60",
                            Name = "Groceries",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("1dbbf7b0-c06e-4c5a-99fe-825010996a1b"),
                            Color = "#34495E",
                            Name = "Rent",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("3b7df4a1-9d8b-48a2-abd7-3cbaf1631d67"),
                            Color = "#BDC3C7",
                            Name = "Utilities",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("367116cf-fa31-4754-b989-8309c0d745a8"),
                            Color = "#E67E22",
                            Name = "Charity",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("aa962b69-f3b7-4e43-bd96-093bbc0b71e9"),
                            Color = "#8E44AD",
                            Name = "Interest",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("ab441d80-a897-4cd5-b50c-52fffda543d2"),
                            Color = "#16A085",
                            Name = "Side Hustle",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("862442fc-2473-47ab-8b92-9182f73f1bbd"),
                            Color = "#D35400",
                            Name = "Insurance",
                            Type = 1
                        });
                });

            modelBuilder.Entity("FP.Domain.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("FP.Domain.Operation", b =>
                {
                    b.HasOne("FP.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
