// <auto-generated />
using System;
using FP.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FP.Infrastructure.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20241105201805_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FP.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea0cd471-45a6-43fc-959f-a79a862dd1ac"),
                            Color = "#FF5733",
                            Name = "Needs"
                        },
                        new
                        {
                            Id = new Guid("e91d46fc-3b57-49d1-b9ea-d103daec6506"),
                            Color = "#FFC300",
                            Name = "Wants"
                        },
                        new
                        {
                            Id = new Guid("96fbede3-2676-4889-bbc3-e7e018bae1ac"),
                            Color = "#28A745",
                            Name = "Savings"
                        },
                        new
                        {
                            Id = new Guid("6af58cb8-81e6-4d4c-95e2-81cb9da2a128"),
                            Color = "#8E44AD",
                            Name = "Subscriptions"
                        },
                        new
                        {
                            Id = new Guid("cb4cbf22-e728-487e-b6e1-f01dda96b8a6"),
                            Color = "#FF6347",
                            Name = "Presents"
                        },
                        new
                        {
                            Id = new Guid("4f330be9-41b5-4229-871b-36853f480b8b"),
                            Color = "#3498DB",
                            Name = "Salary"
                        },
                        new
                        {
                            Id = new Guid("bba28a72-f54e-4ad0-8e2c-7b144e08bc1d"),
                            Color = "#1ABC9C",
                            Name = "Investments"
                        },
                        new
                        {
                            Id = new Guid("7265a21c-80b8-4e12-9e9e-860e4c554918"),
                            Color = "#E74C3C",
                            Name = "Loans"
                        },
                        new
                        {
                            Id = new Guid("3d5fac86-11e6-4aed-b5d5-ea5d399e7837"),
                            Color = "#F39C12",
                            Name = "Bonuses"
                        },
                        new
                        {
                            Id = new Guid("d1b12a7b-9985-40da-b84d-f81c8a3b161b"),
                            Color = "#9B59B6",
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = new Guid("18bdd321-c65c-4bc4-96f8-15883d95fb4a"),
                            Color = "#2ECC71",
                            Name = "Freelance"
                        },
                        new
                        {
                            Id = new Guid("417cfc76-4454-4833-b493-3bca9a62ca97"),
                            Color = "#2980B9",
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("daa73fdd-22ee-4d93-9ebb-f2953633df44"),
                            Color = "#C0392B",
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("77b95a66-8796-4363-93a5-8ce752a238d7"),
                            Color = "#27AE60",
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = new Guid("e53e33d1-afcf-4608-a0cf-c667da634cbc"),
                            Color = "#34495E",
                            Name = "Rent"
                        },
                        new
                        {
                            Id = new Guid("33db6d81-7c07-44a1-bdc8-5684352242fe"),
                            Color = "#BDC3C7",
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = new Guid("e7d28a89-80e4-4071-866e-e97ab2ef29b8"),
                            Color = "#E67E22",
                            Name = "Charity"
                        },
                        new
                        {
                            Id = new Guid("8f0eab38-e186-4801-a2af-14e56494382f"),
                            Color = "#8E44AD",
                            Name = "Interest"
                        },
                        new
                        {
                            Id = new Guid("a0c5ebc9-a9bb-4317-9251-9dfa717dc8fb"),
                            Color = "#16A085",
                            Name = "Side Hustle"
                        },
                        new
                        {
                            Id = new Guid("4f46f8e0-86c3-4b77-acad-60d51c9228d6"),
                            Color = "#D35400",
                            Name = "Insurance"
                        });
                });

            modelBuilder.Entity("FP.Domain.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("FP.Domain.Operation", b =>
                {
                    b.HasOne("FP.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
